# Matugen-generated Keytop palette.
[colors]
surface=#101413
on_surface=#E7EBE9
primary=#5CD6B9
on_surface_variant=#B1BCB8
outline_variant=#4C5854
tertiary=#FFC45C
error=#FFB4AB
primary_container=#005144
on_primary_container=#A0F2DE
secondary=#B1CCC4
